#include <map>

std::map<int, String> student_data{
    { 1, "Bruce Wayne" },
    { 2, "Harvey Dent" },
    { 3, "Alfred Pennyworth" },
    { 4, "James Gordon" },
    { 5, "Rachel Dawes" },
    { 6, "The Joker" },
    { 7, "Lucius Fox" },
    { 8, "Selina Kyle" },
    { 9, "Jonathan Crane" },
    { 10, "Ra's al Ghul" },
    { 11, "Carmine Falcone" },
    { 12, "Sal Maroni" },
    { 13, "Victor Zsasz" },
    { 14, "Barbara Gordon" },
    { 15, "Dick Grayson" },
    { 16, "Jason Todd" },
    { 17, "Tim Drake" },
    { 18, "Damian Wayne" },
    { 19, "Catwoman" },
    { 20, "Two-Face" },
    { 21, "Scarecrow" },
    { 22, "Bane" },
    { 23, "The Penguin" },
    { 24, "The Riddler" },
    { 25, "Mr. Freeze" },
    { 26, "Poison Ivy" },
    { 27, "Harley Quinn" },
    { 28, "The Mad Hatter" },
    { 29, "Ra's al Ghul" },
    { 30, "Hush" }
};